services:
- docker
language: python
python:
- "3.5"
cache: pip
install:
- pip install awscli
script:
- make build
deploy:
  on:
    branch: hugo
  provider: script
  script: make deploy
  skip_cleanup: true
